# Generated by Django 5.2.5 on 2026-02-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_dispolivereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispolivereport',
            name='ambulant_merkmale',
            field=models.BooleanField(default=False, verbose_name='Treatment: outpatient markers'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='andere_transport',
            field=models.BooleanField(default=False, verbose_name='Transport type: other'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='anderer_grund',
            field=models.BooleanField(default=False, verbose_name='Treatment: other reason'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='anderer_grund_ktw',
            field=models.BooleanField(default=False, verbose_name='KTW reason: other'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='arbeitsunfall',
            field=models.BooleanField(default=False, verbose_name='Reason: work accident'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='arzt_nr',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Doctor ID'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='auftraggeber_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ordering party city'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='auftraggeber_info',
            field=models.TextField(blank=True, default='', verbose_name='Ordering party info'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='auftraggeber_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ordering party name'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='auftraggeber_telefon',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Ordering party phone'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='auftraggeber_zip',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Ordering party ZIP'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='ausnahmefall',
            field=models.BooleanField(default=False, verbose_name='Mandatory trip: exceptional case'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='begruendung_sonstiges',
            field=models.TextField(blank=True, default='', verbose_name='Notes / justification'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='betriebsstaetten_nr',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Facility ID'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='bis_voraussichtlich',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Schedule: valid until'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='clinic_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Destination: clinic city'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='clinic_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Destination: clinic name'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='clinic_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Destination: clinic street'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='clinic_zip',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Destination: clinic ZIP'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='datum',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Prescription date'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='dauerhafte_mobilitaet',
            field=models.BooleanField(default=False, verbose_name='Mandatory trip: permanent mobility issues'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='hinfahrt',
            field=models.BooleanField(default=True, verbose_name='Outbound trip'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='hochfrequent',
            field=models.BooleanField(default=False, verbose_name='Mandatory trip: high frequency'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='insurance_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Insurance status'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='kostentraegerkennung',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cost carrier code'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='krankenkasse',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Insurer (Krankenkasse)'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='ktw_medizinisch',
            field=models.BooleanField(default=False, verbose_name='Transport type: KTW (medical)'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='liegend',
            field=models.BooleanField(default=False, verbose_name='Position: lying'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='naw_nef',
            field=models.BooleanField(default=False, verbose_name='Transport type: NAW/NEF'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_birthday',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Patient birth date'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Patient city'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_country',
            field=models.CharField(blank=True, default='D', max_length=50, verbose_name='Patient country'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_name',
            field=models.CharField(error_messages={'max_length': 'Patient first name must not exceed 100 characters.', 'required': 'Patient first name is required.'}, max_length=100, verbose_name='Patient first name'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Patient street'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_surname',
            field=models.CharField(error_messages={'max_length': 'Patient surname must not exceed 100 characters.', 'required': 'Patient surname is required.'}, max_length=100, verbose_name='Patient surname'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Patient phone'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='patient_zip',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Patient ZIP'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='reason_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='KTW reason details'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='rollstuhl',
            field=models.BooleanField(default=False, verbose_name='Position: wheelchair'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='rtw',
            field=models.BooleanField(default=False, verbose_name='Transport type: RTW'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='rueckfahrt',
            field=models.BooleanField(default=True, verbose_name='Return trip'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='show_form',
            field=models.BooleanField(default=True, verbose_name='Show form'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='show_only_filled',
            field=models.BooleanField(default=False, verbose_name='Form: only filled fields'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='taxi_mietwagen',
            field=models.BooleanField(default=False, verbose_name='Transport type: taxi/rental car'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='tragestuhl',
            field=models.BooleanField(default=False, verbose_name='Position: carry chair'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='unfall',
            field=models.BooleanField(default=False, verbose_name='Reason: accident'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='versichertennr',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Insurance number'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='versorgungsleiden',
            field=models.BooleanField(default=False, verbose_name='Reason: care condition'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='vitalzeichenkontrolle',
            field=models.BooleanField(default=False, verbose_name='Transport type: vital monitoring'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='voll_teilstationaer',
            field=models.BooleanField(default=False, verbose_name='Treatment: inpatient full/partial'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='vom_am',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Schedule: valid from'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='vor_nachstationaer',
            field=models.BooleanField(default=False, verbose_name='Treatment: pre/post inpatient'),
        ),
        migrations.AlterField(
            model_name='dispolivereport',
            name='x_pro_woche',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Schedule: times per week'),
        ),
        migrations.CreateModel(
            name='DocumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='document_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='documents.documentupload')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
