# Generated by Django 5.1.5 on 2026-02-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documentupload_dispolive_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispoliveReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_form",
                    models.BooleanField(default=True, verbose_name="Показывать форму"),
                ),
                (
                    "show_only_filled",
                    models.BooleanField(
                        default=False, verbose_name="Только заполненные поля"
                    ),
                ),
                (
                    "patient_surname",
                    models.CharField(
                        error_messages={
                            "max_length": "Макс. 100 символов.",
                            "required": "Фамилия обязательна.",
                        },
                        max_length=100,
                        verbose_name="Nachname",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        error_messages={
                            "max_length": "Макс. 100 символов.",
                            "required": "Имя обязательно.",
                        },
                        max_length=100,
                        verbose_name="Vorname",
                    ),
                ),
                (
                    "patient_street",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Straße"
                    ),
                ),
                (
                    "patient_zip",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "patient_city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Stadt"
                    ),
                ),
                (
                    "patient_country",
                    models.CharField(
                        blank=True, default="D", max_length=50, verbose_name="Land"
                    ),
                ),
                (
                    "patient_birthday",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Geburtsdatum",
                    ),
                ),
                (
                    "patient_telephone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Telefon"
                    ),
                ),
                (
                    "krankenkasse",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Krankenkasse",
                    ),
                ),
                (
                    "kostentraegerkennung",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Kostenträgerkennung",
                    ),
                ),
                (
                    "versichertennr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Versichertennr.",
                    ),
                ),
                (
                    "insurance_status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "betriebsstaetten_nr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Betriebsstätten-Nr.",
                    ),
                ),
                (
                    "arzt_nr",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Arzt-Nr."
                    ),
                ),
                (
                    "datum",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Datum"
                    ),
                ),
                ("unfall", models.BooleanField(default=False, verbose_name="Unfall")),
                (
                    "arbeitsunfall",
                    models.BooleanField(default=False, verbose_name="Arbeitsunfall"),
                ),
                (
                    "versorgungsleiden",
                    models.BooleanField(
                        default=False, verbose_name="Versorgungsleiden"
                    ),
                ),
                (
                    "hinfahrt",
                    models.BooleanField(default=True, verbose_name="Hinfahrt"),
                ),
                (
                    "rueckfahrt",
                    models.BooleanField(default=True, verbose_name="Rückfahrt"),
                ),
                (
                    "voll_teilstationaer",
                    models.BooleanField(
                        default=False, verbose_name="Voll-/Teilstationär"
                    ),
                ),
                (
                    "vor_nachstationaer",
                    models.BooleanField(
                        default=False, verbose_name="Vor-/Nachstationär"
                    ),
                ),
                (
                    "ambulant_merkmale",
                    models.BooleanField(
                        default=False, verbose_name="Ambulant Merkmale"
                    ),
                ),
                (
                    "anderer_grund",
                    models.BooleanField(default=False, verbose_name="Anderer Grund"),
                ),
                (
                    "hochfrequent",
                    models.BooleanField(default=False, verbose_name="Hochfrequent"),
                ),
                (
                    "ausnahmefall",
                    models.BooleanField(default=False, verbose_name="Ausnahmefall"),
                ),
                (
                    "dauerhafte_mobilitaet",
                    models.BooleanField(
                        default=False, verbose_name="Dauerhafte Mobilitätseinschränkung"
                    ),
                ),
                (
                    "anderer_grund_ktw",
                    models.BooleanField(
                        default=False, verbose_name="Anderer Grund KTW"
                    ),
                ),
                (
                    "reason_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Begründung",
                    ),
                ),
                (
                    "vom_am",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Vom/Am"
                    ),
                ),
                (
                    "x_pro_woche",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="X pro Woche",
                    ),
                ),
                (
                    "bis_voraussichtlich",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Bis voraussichtlich",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Klinik Name",
                    ),
                ),
                (
                    "clinic_street",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Klinik Straße",
                    ),
                ),
                (
                    "clinic_zip",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Klinik PLZ"
                    ),
                ),
                (
                    "clinic_city",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Klinik Stadt",
                    ),
                ),
                (
                    "taxi_mietwagen",
                    models.BooleanField(default=False, verbose_name="Taxi/Mietwagen"),
                ),
                (
                    "ktw_medizinisch",
                    models.BooleanField(
                        default=False, verbose_name="KTW (medizinisch)"
                    ),
                ),
                (
                    "vitalzeichenkontrolle",
                    models.BooleanField(
                        default=False, verbose_name="Vitalzeichenkontrolle"
                    ),
                ),
                ("rtw", models.BooleanField(default=False, verbose_name="RTW")),
                ("naw_nef", models.BooleanField(default=False, verbose_name="NAW/NEF")),
                (
                    "andere_transport",
                    models.BooleanField(default=False, verbose_name="Andere"),
                ),
                (
                    "rollstuhl",
                    models.BooleanField(default=False, verbose_name="Rollstuhl"),
                ),
                (
                    "tragestuhl",
                    models.BooleanField(default=False, verbose_name="Tragestuhl"),
                ),
                ("liegend", models.BooleanField(default=False, verbose_name="Liegend")),
                (
                    "auftraggeber_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Auftraggeber Name",
                    ),
                ),
                (
                    "auftraggeber_info",
                    models.TextField(
                        blank=True, default="", verbose_name="Auftraggeber Info"
                    ),
                ),
                (
                    "auftraggeber_zip",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Auftraggeber PLZ",
                    ),
                ),
                (
                    "auftraggeber_city",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Auftraggeber Stadt",
                    ),
                ),
                (
                    "auftraggeber_telefon",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Auftraggeber Telefon",
                    ),
                ),
                (
                    "begruendung_sonstiges",
                    models.TextField(
                        blank=True, default="", verbose_name="Begründung/Sonstiges"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dispolive Report",
                "verbose_name_plural": "Dispolive Reports",
            },
        ),
        migrations.AlterField(
            model_name="documentupload",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("uploaded", "uploaded"),
                    ("processing", "processing"),
                    ("pending_review", "pending_review"),
                    ("done", "done"),
                    ("error", "error"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentupload",
            name="dispolive_report",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document",
                to="documents.dispolivereport",
            ),
        ),
    ]
