# Generated by Django 5.2.5 on 2025-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='candidates/avatars'),
        ),
        migrations.AddField(
            model_name='hr',
            name='avatar',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='hr/avatars'),
        ),
    ]
