# Generated by Django 5.2.5 on 2025-11-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_candidate_avatar_hr_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
