# Generated by Django 5.2.5 on 2025-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_candidate_city_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
