# Generated by Django 5.2.5 on 2025-11-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('Response', 'Response'), ('Contacts', 'Contacts')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('Telegram', 'Telegram'), ('Test', 'Test'), ('Trainee', 'Trainee'), ('Working', 'Working'), ('Refuse', 'Refuse')], max_length=20, null=True),
        ),
    ]
