# Generated by Django 5.2.5 on 2025-11-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_department_slug_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Telegram', 'Telegram'), ('Test', 'Test'), ('Trainee', 'Trainee'), ('Working', 'Working'), ('Refuse', 'Refuse')], default='New', max_length=20, null=True),
        ),
    ]
