# Generated by Django 5.2.5 on 2025-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
