# Generated by Django 5.2.5 on 2025-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_candidatecomment_hrcomment_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
