# Generated by Django 5.2.5 on 2025-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_candidate_first_name_alter_candidate_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
