# Generated by Django 5.2.5 on 2025-12-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_candidate_age_candidate_birth_date_candidate_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='birth_date',
        ),
    ]
