# Generated by Django 5.2.5 on 2025-12-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_remove_candidate_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
