# Generated by Django 5.2.5 on 2025-12-04 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_candidate_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 10, 39, 50, 750665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Telegram', 'Telegram'), ('No Answer', 'No Answer'), ('Test', 'Test'), ('Trainee', 'Trainee'), ('Working', 'Working'), ('Refuse', 'Refuse')], default='New', max_length=20, null=True),
        ),
    ]
