# Generated by Django 5.2.5 on 2025-12-04 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_alter_candidate_created_at_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 12, 38, 52, 541517, tzinfo=datetime.timezone.utc)),
        ),
    ]
