# Generated by Django 5.2.5 on 2025-12-04 14:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_candidate_photo_link_alter_candidate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 14, 5, 51, 667795, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('Response', 'Response'), ('Contacts', 'Contacts'), ('Applied', 'Applied')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.department')),
            ],
        ),
    ]
