# Generated by Django 5.2.5 on 2025-12-04 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_alter_candidate_created_at_alter_candidate_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 17, 21, 19, 420443, tzinfo=datetime.timezone.utc)),
        ),
    ]
