# Generated by Django 5.2.5 on 2026-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('done', 'done'), ('error', 'error')], default='uploaded', max_length=20),
        ),
    ]
