# Generated by Django 5.2.5 on 2026-02-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentupload_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='dispolive_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
